// Generated by gencpp from file pkg_task0/MoveCircleResponse.msg
// DO NOT EDIT!


#ifndef PKG_TASK0_MESSAGE_MOVECIRCLERESPONSE_H
#define PKG_TASK0_MESSAGE_MOVECIRCLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_task0
{
template <class ContainerAllocator>
struct MoveCircleResponse_
{
  typedef MoveCircleResponse_<ContainerAllocator> Type;

  MoveCircleResponse_()
    {
    }
  MoveCircleResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::pkg_task0::MoveCircleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_task0::MoveCircleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveCircleResponse_

typedef ::pkg_task0::MoveCircleResponse_<std::allocator<void> > MoveCircleResponse;

typedef boost::shared_ptr< ::pkg_task0::MoveCircleResponse > MoveCircleResponsePtr;
typedef boost::shared_ptr< ::pkg_task0::MoveCircleResponse const> MoveCircleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_task0::MoveCircleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_task0::MoveCircleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace pkg_task0

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pkg_task0::MoveCircleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_task0::MoveCircleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_task0::MoveCircleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_task0::MoveCircleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_task0::MoveCircleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_task0::MoveCircleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_task0::MoveCircleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pkg_task0::MoveCircleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_task0::MoveCircleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_task0/MoveCircleResponse";
  }

  static const char* value(const ::pkg_task0::MoveCircleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_task0::MoveCircleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::pkg_task0::MoveCircleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_task0::MoveCircleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveCircleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_task0::MoveCircleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::pkg_task0::MoveCircleResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PKG_TASK0_MESSAGE_MOVECIRCLERESPONSE_H
