// Generated by gencpp from file pkg_task0/MoveSquare.msg
// DO NOT EDIT!


#ifndef PKG_TASK0_MESSAGE_MOVESQUARE_H
#define PKG_TASK0_MESSAGE_MOVESQUARE_H

#include <ros/service_traits.h>


#include <pkg_task0/MoveSquareRequest.h>
#include <pkg_task0/MoveSquareResponse.h>


namespace pkg_task0
{

struct MoveSquare
{

typedef MoveSquareRequest Request;
typedef MoveSquareResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveSquare
} // namespace pkg_task0


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg_task0::MoveSquare > {
  static const char* value()
  {
    return "af0b48fe9187ad9b8874f8bb3dcfb81d";
  }

  static const char* value(const ::pkg_task0::MoveSquare&) { return value(); }
};

template<>
struct DataType< ::pkg_task0::MoveSquare > {
  static const char* value()
  {
    return "pkg_task0/MoveSquare";
  }

  static const char* value(const ::pkg_task0::MoveSquare&) { return value(); }
};


// service_traits::MD5Sum< ::pkg_task0::MoveSquareRequest> should match
// service_traits::MD5Sum< ::pkg_task0::MoveSquare >
template<>
struct MD5Sum< ::pkg_task0::MoveSquareRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_task0::MoveSquare >::value();
  }
  static const char* value(const ::pkg_task0::MoveSquareRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_task0::MoveSquareRequest> should match
// service_traits::DataType< ::pkg_task0::MoveSquare >
template<>
struct DataType< ::pkg_task0::MoveSquareRequest>
{
  static const char* value()
  {
    return DataType< ::pkg_task0::MoveSquare >::value();
  }
  static const char* value(const ::pkg_task0::MoveSquareRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg_task0::MoveSquareResponse> should match
// service_traits::MD5Sum< ::pkg_task0::MoveSquare >
template<>
struct MD5Sum< ::pkg_task0::MoveSquareResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_task0::MoveSquare >::value();
  }
  static const char* value(const ::pkg_task0::MoveSquareResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_task0::MoveSquareResponse> should match
// service_traits::DataType< ::pkg_task0::MoveSquare >
template<>
struct DataType< ::pkg_task0::MoveSquareResponse>
{
  static const char* value()
  {
    return DataType< ::pkg_task0::MoveSquare >::value();
  }
  static const char* value(const ::pkg_task0::MoveSquareResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG_TASK0_MESSAGE_MOVESQUARE_H
