// Generated by gencpp from file pkg_task0/MoveCircle.msg
// DO NOT EDIT!


#ifndef PKG_TASK0_MESSAGE_MOVECIRCLE_H
#define PKG_TASK0_MESSAGE_MOVECIRCLE_H

#include <ros/service_traits.h>


#include <pkg_task0/MoveCircleRequest.h>
#include <pkg_task0/MoveCircleResponse.h>


namespace pkg_task0
{

struct MoveCircle
{

typedef MoveCircleRequest Request;
typedef MoveCircleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveCircle
} // namespace pkg_task0


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg_task0::MoveCircle > {
  static const char* value()
  {
    return "6d766f6a2db01255c7ae96df4f8888c5";
  }

  static const char* value(const ::pkg_task0::MoveCircle&) { return value(); }
};

template<>
struct DataType< ::pkg_task0::MoveCircle > {
  static const char* value()
  {
    return "pkg_task0/MoveCircle";
  }

  static const char* value(const ::pkg_task0::MoveCircle&) { return value(); }
};


// service_traits::MD5Sum< ::pkg_task0::MoveCircleRequest> should match
// service_traits::MD5Sum< ::pkg_task0::MoveCircle >
template<>
struct MD5Sum< ::pkg_task0::MoveCircleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_task0::MoveCircle >::value();
  }
  static const char* value(const ::pkg_task0::MoveCircleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_task0::MoveCircleRequest> should match
// service_traits::DataType< ::pkg_task0::MoveCircle >
template<>
struct DataType< ::pkg_task0::MoveCircleRequest>
{
  static const char* value()
  {
    return DataType< ::pkg_task0::MoveCircle >::value();
  }
  static const char* value(const ::pkg_task0::MoveCircleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg_task0::MoveCircleResponse> should match
// service_traits::MD5Sum< ::pkg_task0::MoveCircle >
template<>
struct MD5Sum< ::pkg_task0::MoveCircleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_task0::MoveCircle >::value();
  }
  static const char* value(const ::pkg_task0::MoveCircleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_task0::MoveCircleResponse> should match
// service_traits::DataType< ::pkg_task0::MoveCircle >
template<>
struct DataType< ::pkg_task0::MoveCircleResponse>
{
  static const char* value()
  {
    return DataType< ::pkg_task0::MoveCircle >::value();
  }
  static const char* value(const ::pkg_task0::MoveCircleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG_TASK0_MESSAGE_MOVECIRCLE_H
